on:
  push:
    branches:
      - master
    paths-ignore:
      - '.idea/**'
      - 'docs/**'
      - 'examples/**'
      - 'extras/**'
      - 'script/**'
      - .dockerignore
      - .gitignore
      - Dockerfile
      - LICENSE
      - README.md
      - skija.iml

jobs:
  shared:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.8'
      - run: ./ci/deploy_shared.sh
        env:
          SPACE_TOKEN: ${{ secrets.SPACE_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: skija-shared
          path: shared/target/*.jar

  macos:
    runs-on: macos-10.15
    needs: shared
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.8'
      - run: ./native/script/build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: skija-macos
          path: native/build/*.dylib
      - run: ./ci/deploy_macos.sh
        env:
          SPACE_TOKEN: ${{ secrets.SPACE_TOKEN }}

  linux:
    runs-on: ubuntu-latest
    container: tonsky/ubuntu-14.04:latest
    needs: shared
    steps:
      - run: |
          echo "/usr/lib/binutils-2.26/bin" >> $GITHUB_PATH
          echo "/root/apache-maven-3.6.3/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          echo "+++++++++++++PWD: ${PWD}++++++++++++++++++"
          cat ./native/script/build.sh
          ./native/script/build.sh
          ls -lh .
          ls -lh native/build
      - uses: actions/upload-artifact@v2
        with:
          name: skija-linux
          path: native/build/*.so
      - run: ./ci/deploy_linux.sh
        env:
          SPACE_TOKEN: ${{ secrets.SPACE_TOKEN }}

  windows:
    runs-on: windows-2019
    needs: shared
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: microsoft/setup-msbuild@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.8'
      - shell: bash
        run: ./native/script/build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: skija-windows
          path: |
            native/build/*.dll
            native/build/icudtl.dat
      - shell: bash
        run: ./ci/deploy_windows.sh
        env:
          SPACE_TOKEN: ${{ secrets.SPACE_TOKEN }}
